audit: 1

uri_base: "http://localhost:5001"

api:
  v1:
    token_secret: testsecret

default_lang: en
default_page_size: 20
default_searchpage_size: 10
maximum_page_size: 1000
pagination_options:
  - 10
  - 20
  - 50
  - 100
sort_options:
  - year
  - date_updated
  - title
  - author
  - type
  - publication
sort_options_person:
  - fullname
  - publcount
project_sort_options:
  - name
  - acronym
  - startyear
default_sort:
  - year.desc
default_sort_backend:
  - date_updated.desc
  - year.desc
default_person_sort:
  - lastname.asc
facets:
  publication:
    open_access:
      terms:
        field: 'oa'
        size: 1
    popular_science:
      terms:
        field: 'popular_science'
        size: 1
    extern:
      terms:
        field: 'extern'
        size: 2
    status:
      terms:
        field: 'status'
        size: 8
    year:
      terms:
        field: 'year'
        size: 100
        order: {_key: desc}
    type:
      terms:
        field: 'type'
        size: 25
    isi:
      terms:
        field: 'isi'
        size: 1
    pmid:
      terms:
        field: 'pmid'
        size: 1

request_copy:
  # period in days
  period: 7
  subject: 'Request for a copy of your publication'

# Default format to display dates
time_format: "%Y-%m-%dT%H:%M:%SZ"

# Prefix used for local generated URNs
urn_prefix: 'urn:whatever-'

# Use this link to lookup a personId in a staff directory. Required
# to differentiate between different users with the same name (homonym,namesake)
person:
  staffdirectory: "http://www.librecat.org/?personId="

# Default access level for uploaded files
default_access_level: open_access

## Specity the ipranges which can download (local) files
ip_range:
    - 157.193.0.0/16
    - 127.0.0.1
    - 10.0.0.0/8

authentication:
  package: LibreCat::Auth::Multi
  options:
    methods:
      # password auth against users in config
      - package: LibreCat::Auth::Bag
        options:
          store: builtin_users
          username_attr: login
      # password auth against database users
      - package: LibreCat::Auth::Bag
        options:
          store: search
          bag: user
          username_attr: login

user:
  sources:
    - store: builtin_users
      username_attr: login
    - store: search
      bag: user
      username_attr: login

api:
  v1:
    token_secret: 'ANCCgnD6XUGGLvE0CBKu8pbcHDqXVMRKTD1Q8Iu7JyS1TefYZ7dQovhL9iERYcw'

citation:
  engine: none

store:
  main:
    package: DBI
    options:
      data_source: "dbi:SQLite:dbname=t/tmp/librecat_test.sqlite3"

  search:
    options:
      bags:
        department:
          index: librecat_test_department
        project:
          index: librecat_test_project
        publication:
          index: librecat_test_publication
        research_group:
          index: librecat_test_research_group
        user:
          index: librecat_test_user

  builtin_users:
    package: Hash
    options:
      init_data:
        # stored password authentication
        - login: einstein
          # password is same as login
          # crypt a password with 'bmkpasswd [password]' in the shell
          password: '$2a$08$p1zhJInkNqy9nvMFsEPde./hU4ERNQuX2UQUjZA/ddrp1uUXikn/6'
          _id: 1234
          super_admin: 1
          account_status: active
        - login: mozart
          password: '$2a$08$bfC3ySsDzgy/mEV/GrxL6uRCRn4Fnb25l5z16XVedP2i7aJE8MEDG'
          _id: 5678
          account_status: inactive

filestore:
    default: &filestore_settings
        package: Simple
        options:
            root: t/data
    test:
        package: Simple
        options:
            root: t/data2
    uploader:
        package: 'LibreCat::Worker::FileUploader'
        options:
            files: *filestore_settings

    download_headers:
      for_all:
        "Content-Disposition": "attachment; filename*=UTF-8''%s"
      for_content_type:
        "text/plain":
          "Content-Disposition": "inline; filename*=UTF-8''%s"
          "Content-Type": "%s; charset=utf-8"

hooks:
  eat:
   before_fixes: [peckish, hungry]
   after_fixes: [satisfied]

i18n:
  lexicon:
    en:
      - CatmanduConfig
      - ['en']

locale:
  en:
    hello: How are you?

helper_plugins:
  - MyHelperPlugin

log4perl: |
  log4perl.category.LibreCat::Auth=WARN,FILE
  log4perl.category.LibreCat::Worker=WARN,FILE
  log4perl.category.LibreCat::App=WARN,FILE
  log4perl.category.LibreCat::Hook=WARN,FILE
  log4perl.category.LibreCat::FetchRecord=WARN,FILE
  log4perl.category.LibreCat::Search=WARN,FILE
  log4perl.category.LibreCat::Queue=WARN,FILE
  log4perl.category.T::Logger=DEBUG,FILE
  log4perl.appender.FILE=Log::Log4perl::Appender::File
  log4perl.appender.FILE.filename=/dev/null
  log4perl.appender.FILE.utf8=1
  log4perl.appender.FILE.layout=SimpleLayout
