uri_base: "http://localhost:5001"

default_lang: en
default_page_size: 20
default_searchpage_size: 10
maximum_page_size: 1000
pagination_options:
  - 10
  - 20
  - 50
  - 100
sort_options:
  - year
  - date_updated
  - title
  - author
  - type
  - publication
sort_options_person:
  - fullname
  - publcount
project_sort_options:
  - name
  - acronym
  - startyear
default_sort:
  - year.desc
default_sort_backend:
  - date_updated.desc
  - year.desc
default_person_sort:
  - lastname.asc
default_facets:
    open_access:
      terms:
        field: 'file.open_access'
        size: 1
    popular_science:
      terms:
        field: 'popular_science'
        size: 1
    extern:
      terms:
        field: 'extern'
        size: 2
    status:
      terms:
        field: 'status'
        size: 8
    year:
      terms:
        field: 'year'
        size: 100
        order: 'reverse_term'
    type:
      terms:
        field: 'type'
        size: 25
    isi:
      terms:
        field: 'isi'
        size: 1
    pmid:
      terms:
        field: 'pmid'
        size: 1

request_copy:
  # period in days
  period: 7
  subject: 'Request for a copy of your publication'

# Default format to display dates
time_format: "%Y-%m-%dT%H:%M:%SZ"

# Prefix used for local generated URNs
urn_prefix: 'urn:whatever-'

# Use this link to lookup a personId in a staff directory. Required
# to differentiate between different users with the same name (homonym,namesake)
person:
  staffdirectory: "http://www.librecat.org/?personId="

# Default access level for uploaded files
default_access_level: open_access

urn_prefix: 'urn:test-'

## Specity the ipranges which can download (local) files
ip_range:
    - 157.193.0.0/16
    - 127.0.0.1
    - 10.0.0.0/8

authentication:
  package: LibreCat::Auth::Multi
  options:
    methods:
      # password auth against users in config
      - package: LibreCat::Auth::Bag
        options:
          store: builtin_users
          username_attr: login
      # password auth against database users
      - package: LibreCat::Auth::Bag
        options:
          store: search
          bag: user
          username_attr: login

user:
  sources:
    - store: builtin_users
      username_attr: login
    - store: search
      bag: user
      username_attr: login

citation:
  engine: none

store:
  main:
    package: DBI
    options:
      data_source: "dbi:SQLite:dbname=t/tmp/librecat_test.sqlite3"

  search:
    options:
      client: '1_0::Direct'
      index_name: librecat_test
  builtin_users:
    package: Hash
    options:
      init_data:
        # stored password authentication
        - login: einstein
          # password is same as login
          # crypt a password with 'bmkpasswd [password]' in the shell
          password: '$2a$08$p1zhJInkNqy9nvMFsEPde./hU4ERNQuX2UQUjZA/ddrp1uUXikn/6'
          _id: 1234
          super_admin: 1
          account_status: active

filestore:
    default: &filestore_settings
        package: Simple
        options:
            root: t/data
    test:
        package: Simple
        options:
            root: t/data2
    uploader:
        package: 'LibreCat::Worker::FileUploader'
        options:
            files: *filestore_settings
hooks:
  eat:
   before_fixes: [peckish, hungry]
   after_fixes: [satisfied]

i18n:
  lexicon:
    en:
      - CatmanduConfig
      - ['en']

locale:
  en:
    hello: How are you?

queue:
  workers:
    audit:
      count: 1
      supervise: 1

worker:
    logdir: /tmp
