sudo: required
dist: trusty
language: perl

perl:
  - "5.24"
  - "5.22"

cache:
  directories:
    - perl_modules

env:
matrix:
  include:
    - perl: "5.26"
      env: GEARMAN_NETWORK_TEST=1 NETWORK_TEST=1
  allow_failures:
    - perl: "5.26"
      env: GEARMAN_NETWORK_TEST=1 NETWORK_TEST=1

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart
  - sudo apt-get install --yes --force-yes gearman gearman-tools gearman-job-server libgearman-dev
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

before_script:
  - sleep 3

service:
  - sqlite3

install:
  - cpanm --quiet --installdeps --notest --force .
  - cpanm --quiet --notest Devel::Cover

script:
  - cover -t +select ^lib +ignore ^ -make 'prove -Ilib -j 2 -r t; exit $?'

after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls

notifications:
  email: false
  slack: librecat:2Rvl147KSMvEdivUg88Ktrbk
