time_format: "%Y-%m-%dT%H:%M:%SZ"

# Specity the ipranges which can download (local) files
ip_range:
    - 127.0.0.1
    - 10.0.0.0/8

urn_prefix: 'urn:whatever-'

# Use this link to lookup a personId in a staff directory. Required
# to differentiate between different users with the same name (homonym,namesake)
person:
  staffdirectory: "https://ekvv.uni-bielefeld.de/pers_publ/publ/PersonDetail.jsp?personId="

## Uncomment when you want to send emails when new research data becomes available
#research_data:
#  to: 'send@me.org'
#  subject: '[PUB] New research data submitted'

## Uncomment when you want to register your research_data DOI at DataCite
#doi:
#  prefix: "10.5072/test"
#  user: user
#  passwd: secret

# default settings
default_lang: en
default_page_size: 20
default_searchpage_size: 10
maximum_page_size: 1000
pagination_options:
  - 10
  - 20
  - 50
  - 100
sort_options:
  - year
  - date_updated
  - title
  - author
  - type
  - publication
sort_options_person:
  - fullname
  - publcount
project_sort_options:
  - name
  - acronym
  - startyear
default_sort:
  - year.desc
  - date_updated.desc
default_sort_backend:
  - date_updated.desc
  - year.desc
default_style: 'default'
default_fd_style: 'default'
default_format: html

default_facets:
  # author:
  #   terms:
  #     field: 'author.id'
  #     size: 20
  # editor:
  #   terms:
  #     field: 'editor.id'
  #     size: 20
  open_access:
    terms:
      field: 'file.open_access'
      size: 1
  popular_science:
    terms:
      field: 'popular_science'
      size: 1
  extern:
    terms:
      field: 'extern'
      size: 2
  status:
    terms:
      field: 'status'
      size: 8
  year:
    terms:
      field: 'year'
      size: 100
      order: 'reverse_term'
  type:
    terms:
      field: 'type'
      size: 25
  isi:
    terms:
      field: 'isi'
      size: 1
  pmid:
    terms:
      field: 'pmid'
      size: 1

request_copy:
# period in days
  period: 7
  subject: 'Request for a copy of your publication'

audit: 0
