_prefix:
  citation:

# engine for citation generation
# possible values are 'csl' or 'none'
engine: no

# example 'csl' style citation generation
# see: https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language
csl:
  url: 'http://localhost:8085'
  default_style: short
  styles:
    apa: apa
    ama: american-medical-association
    chicago: chicago-fullnote-bibliography
    ieee: ieee
    mla: modern-language-association
    short: elsevier-without-titles
