---
_prefix:
  filestore:

#  Configurable name of the download file
#  options:
#     %i: publication id
#     %o: original file name
#     %f: file_id
#     %e: extension
#  The download name can be a combination like ""%i-%f.%e"
download_file_name: "%o"

# Override http headers for download
#
# Note that there are already builtin defaults
#download_headers:
#  # ..for all content-types
#  for_all:
#    # the '%s' is replaced by the current content-type
#    "Content-Type": "%s"
#    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0"
#    "Pragma": "no-cache"
#    # the '%s' is replaced by the current filename
#    "Content-Disposition": "inline; filename*=UTF-8''%s"
#  # ..for specific content-types (overrides previous)
#  for_content_type:
#    "text/plain":
#      "Content-Type": "%s; charset=utf-8"

# Main location of all the uploaded files
default: &filestore_settings
    # Options for the default store:
    #   - Simple
    #   - BagIt (requires Catmandu::BagIt)
    #   - Multi (requires in store.yml definitions of multiple file stores)
    package: Simple
    options:
        # Optional calculate MD5 checksums on the fly
        # default_plugins: [ 'DynamicChecksum' ]
        root: data/file_uploads

# Main locaton of all thumbnail images
access: &accessstore_settings
    package: Simple
    options:
        root: data/file_uploads

# Main location of all temporary uploads
temp: &tempstore_settings
    # Mandatory: temp store need to be a Simple store
    package: Simple
    options:
        root: data/temp_uploads
        # Automatic clean up of temporary uploads when they are archived
        autocleanup: 1
        # Create a date based mapping of temporary data on disk
        directory_index_package: Map
        # Database to store the path mappings
        directory_index_options:
            store_name: main
            bag_name: temp_files

# Worker that imports/deletes files from the filestore
uploader:
    package: 'LibreCat::Worker::FileUploader'
    options:
        files: *filestore_settings
        temp_files: *tempstore_settings

# Worker that generates thumbnail files
access_thumbnailer:
    package: 'LibreCat::Worker::ImageResizer'
    options:
        files: *filestore_settings
        access: *accessstore_settings

# Which ip-ranges can access the file api (not for end-users)
api:
    buffer_size: 8192
    access:
        ip_range:
            - 127.0.0.1
            - 10.0.0.0/8
